import { Inter } from "next/font/google";
import "./globals.css";
import "./extra.css";
import "/bg.css"
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={'w-full h-full flex flex-col'}>
          <NavBar/>
        {children}
          <div className={'w-full h-[1000px]'}></div>
      </div>
      </body>
    </html>
  );
}
